<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260920064646 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Adds the table behind pending email changes';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE email_change_request (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, new_email VARCHAR(180) NOT NULL, expires_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, token VARCHAR(64) NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_136F31FF5F37A13B ON email_change_request (token)');
        $this->addSql('CREATE INDEX IDX_136F31FFA76ED395 ON email_change_request (user_id)');
        $this->addSql('ALTER TABLE email_change_request ADD CONSTRAINT FK_136F31FFA76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE email_change_request DROP CONSTRAINT FK_136F31FFA76ED395');
        $this->addSql('DROP TABLE email_change_request');
    }
}
